#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math

# Trying to ensure that data is less than 1500 bytes
DATA_SIZE = 1375

class Sender:
    
    def __init__(self, host, port):
        self.host = host
        self.port = int(port)
        self.log("Sender starting up using port %s" % self.port)
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))

        self.window_size = 4
        self.consecutive_acks = 0
        self.in_flight = {}
        self.next_seq = 0
        
        # Adaptive timeout variables
        self.estimated_rtt = 0.5
        self.rttDeviation = 0.25 
        self.timeout = 1.0 
        
        self.remote_host = None
        self.remote_port = None

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def send(self, message):
        self.log("Sending message '%s'" % json.dumps(message))
        self.socket.sendto(json.dumps(message).encode("utf-8"), (self.host, self.port))

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        if self.remote_host is None:
            self.remote_host = addr[0]
            self.remote_port = addr[1]

        if addr != (self.remote_host, self.remote_port):
            self.log("Error: Received response from unexpected remote; ignoring")
            return None
        else:
            self.log("Received message %s" % data.decode("utf-8"))
            return json.loads(data.decode("utf-8"))

    """
    Update timeout based on measured RTT using TCP's algorithm:
    - estimated_rtt = 0.875 * estimated_rtt + 0.125 * sample_rtt
    - dev_rtt = 0.75 * dev_rtt + 0.25 * |sample_rtt - estimated_rtt|
    - timeout = estimated_rtt + 4 * dev_rtt
    Referenced from: https://www.rfc-editor.org/rfc/rfc6298.html
    """
    def update_timeout(self, sample_rtt):
        
        self.estimated_rtt = 0.875 * self.estimated_rtt + 0.125 * sample_rtt
        self.rttDeviation = 0.75 * self.rttDeviation + 0.25 * abs(sample_rtt - self.estimated_rtt)
        self.timeout = self.estimated_rtt + 4 * self.rttDeviation
        self.timeout = max(0.5, min(self.timeout, 5.0))
        
        self.log(f"Updated timeout: RTT={sample_rtt:.3f}s, estimated RTT={self.estimated_rtt:.3f}s, RTT deviation={self.rttDeviation:.3f}s, Timeout={self.timeout:.3f}s")

    def run(self):
        while True:
            # Check for timeouts and retransmit
            current_time = time.time()
            timeout_occurred = False
            
            for seq, packet_info in list(self.in_flight.items()):
                if current_time - packet_info['time'] > self.timeout:
                    self.log(f"Timeout for packet {seq}, retransmitting")
                    self.send(packet_info['msg'])
                    packet_info['time'] = current_time
                    timeout_occurred = True
            
            # Only decrease window once per iteration if any timeouts occurred
            if timeout_occurred:
                old_window = self.window_size
                self.window_size = max(2, self.window_size // 2)
                self.consecutive_acks = 0
                self.log(f"Decreased window from {old_window} to {self.window_size}")

            # Determine what sockets to monitor
            can_send = len(self.in_flight) < self.window_size
            sockets = [self.socket, sys.stdin] if can_send else [self.socket]

            socks = select.select(sockets, [], [], 0.1)[0]
            
            for conn in socks:
                if conn == self.socket:
                    # Received ACK
                    data = self.recv(conn)
                    if data and data.get('type') == 'ack':
                        ack_seq = data['seq']
                        if ack_seq in self.in_flight:
                            # Measure RTT for this packet
                            sample_rtt = time.time() - self.in_flight[ack_seq]['time']
                            self.update_timeout(sample_rtt)
                            
                            self.log(f"Got ACK for packet {ack_seq}")
                            del self.in_flight[ack_seq]
                            
                            # Increase window on successful ACKs
                            self.consecutive_acks += 1
                            if self.consecutive_acks >= 5 and self.window_size < 20:
                                self.window_size += 1
                                self.consecutive_acks = 0
                                self.log(f"Increased window to {self.window_size}")
                        
                elif conn == sys.stdin:
                    # Read and send new data
                    data = sys.stdin.read(DATA_SIZE)
                    if len(data) == 0:
                        # Wait for all ACKs before exiting
                        if len(self.in_flight) == 0:
                            self.log("All done!")
                            sys.exit(0)
                    else:
                        msg = {"type": "msg", "data": data, "seq": self.next_seq}
                        self.send(msg)
                        self.in_flight[self.next_seq] = {'msg': msg, 'time': time.time()}
                        self.next_seq += 1

        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('host', type=str, help="Remote host to connect to")
    parser.add_argument('port', type=int, help="UDP port number to connect to")
    args = parser.parse_args()
    sender = Sender(args.host, args.port)
    sender.run()